---
- hosts: ansibleserver
  roles:
    - create_certificates

- hosts: servers
  roles:
    - install_docker

- hosts: registrar
  roles:
    - deploy_registrar

- hosts: ballotbox
  roles:
    - deploy_ballotbox

- hosts: ballotserver
  roles:
    - deploy_ballotserver

- hosts: resultserver
  roles:
    - deploy_resultserver
