---
- name: Template env_file
  ansible.builtin.template:
    src: env_file.j2
    dest: "{{ app_repository_directory }}/docker/env_file"

- name: Template secret_config.py
  ansible.builtin.template:
    src: config.py.j2
    dest: "{{ app_repository_directory }}/app/secret_config.py"

- name: Copy over election manifest
  ansible.builtin.copy:
    src: "{{ election_manifest_file_path }}"
    dest: "{{ app_repository_directory }}/app/data/manifest.json"

- name: Copy over private key
  ansible.builtin.copy:
    src: "{{ ca_directory }}/ballotserver/ballotserver.key"
    dest: "{{ app_repository_directory }}/docker/server.key"

- name: Copy over certificate
  ansible.builtin.copy:
    src: "{{ ca_directory }}/ballotserver/ballotserver.crt"
    dest: "{{ app_repository_directory }}/docker/server.crt"

- name: Copy over CA certificate
  ansible.builtin.copy:
    src: "{{ ca_directory }}/ca.crt"
    dest: "{{ app_repository_directory }}/docker/ca.crt"