---
- name: Template env_file
  ansible.builtin.template:
    src: env_file.j2
    dest: "{{ app_repository_directory }}/docker/env_file"

- name: Copy over election manifest
  ansible.builtin.copy:
    src: "{{ election_manifest_file_path }}"
    dest: "{{ app_repository_directory }}/app/data/manifest.json"
