---
- name: Configure service to operate under user
  when: use_compose_service_user
  block:
    - name: Create service user
      ansible.builtin.user:
        name: "{{ compose_service_name }}"
        shell: /usr/sbin/nologin
        home: "{{ compose_service_directory }}"
        groups:
          - docker

    - name: Grant service user ownership of repository directory
      ansible.builtin.file:
        path: "{{ compose_service_directory }}"
        recurse: true
        owner: "{{ compose_service_name }}"
        group: "{{ compose_service_name }}"
