---
- name: Template config.py
  ansible.builtin.template:
    src: config.py.j2
    dest: "{{ app_repository_directory }}/app/config.py"
  vars:
    ansible_become: no

- name: Template secret_config.py
  ansible.builin.template:
    src: secret_config.py.j2
    dest: "{{ app_repository_directory }}/app/secret_config.py"
  vars:
    ansible_become: no

- name: Ensure Data directory exists
  ansible.builtin.file:
    path: "{{ app_repository_directory }}/data"
    state: directory
  vars:
    ansible_become: no

- name: Copy over registrar voter data file
  ansible.builtin.copy:
    src: "{{ voter_registrarion_data_file_path }}"
    dest: "{{ app_repository_directory }}/data/voter_data.json"
  vars:
    ansible_become: no
  