---
- name: Template env_file
  ansible.builtin.template:
    src: env_file.j2
    dest: "{{ app_repository_directory }}/docker/env_file"

- name: Ensure Data directory exists
  ansible.builtin.file:
    path: "{{ app_repository_directory }}/data"
    state: directory

- name: Copy over registrar voter data file
  ansible.builtin.copy:
    src: "{{ voter_registration_data_file_path }}"
    dest: "{{ app_repository_directory }}/data/voter_data.json"
