---
- name: Prerequisite setup
  ansible.builtin.include_tasks: prereqs.yaml

- name: Install application
  ansible.builtin.include_role:
    name: install_application

- name: Configure application
  ansible.builtin.include_tasks: configure.yaml

- name: Setup application as service
  ansible.builtin.include_role:
    name: install_compose_application_as_service
