---
- name: Create server certificate directory
  ansible.builtin.file:
    path: "{{ ca_directory }}/{{ item }}"
    state: directory  

- name: Create server key
  community.crypto.openssl_privatekey:
    path: "{{ ca_directory }}/{{ item }}/{{ item }}.key"

- name: Create server csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ca_directory }}/{{ item }}/{{ item }}.key"
    common_name: "{{ hostvars[item].ansible_host }}"
    subject_alt_name:
    {% if hostvars[item].ansible_host | ipaddr %}
      - "IP Address:{{ hostvars[item].ansible_host }}"
    {% else %}
      - "DNS:{{ hostvars[item].ansible_host }}"
    {% endif %}
  register: csr

- name: Create server cert
  community.crypto.x509_certificate:
    path: "{{ ca_directory }}/{{ item }}/{{ item }}.crt"
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ ca_directory }}/ca.crt"
    ownca_privatekey_path: "{{ ca_directory }}/ca.key"
    ownca_privatekey_passphrase: "{{ ca_passphrase }}"
    ownca_not_after: "+365d"
    ownca_not_before: "-1d"
